<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Failed</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>98d55080-54fd-4e65-916b-244ff858106a</testSuiteGuid>
   <testCaseLink>
      <guid>f0957692-0373-461c-b7a5-58712f8dba5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Failed/Login gagal - usnamepwd kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266bf02a-f238-4401-9f15-dc7c858bee00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfcd254b-b3f5-4c9e-8337-d19e2ff10d66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97845eb3-993a-4628-93b3-f96b91a2a44a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Failed/Login gagal - pwd kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1572f5d7-9f98-4c4b-9385-e7d3aff029a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a496b28-c73c-47d4-8df2-734dfdde7fd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0e0da60-7181-4812-bed7-014e65671d0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Failed/Login gagal - username kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5843a2a6-6efa-4f8f-ab2d-a78c0b6ad963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3288652-c464-498f-95c5-e4241e36fb6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e74ad3d5-ce55-47ef-85d2-2cf0403bf81a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Failed/Login gagal - invalid creds</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>067a095c-00eb-4b89-8d36-9a2269dda2c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38a3bc1c-574b-4cb3-b2d8-f31a7a08cc6a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
